{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "aravanta-cloudos.fullname" . }}
  labels:
    app.kubernetes.io/name: aravanta-ingress
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            pathType: {{ .pathType }}
            backend:
              service:
                name: {{ include "aravanta-cloudos.fullname" $ }}-{{ .backendService }}
                port:
                  number: {{ if eq .backendService "backend" }}{{ $.Values.service.backendPort }}{{ else }}{{ $.Values.service.frontendPort }}{{ end }}
          {{- end }}
    {{- end }}
{{- end }}
